### ISSUE TITLE
asdf plugin

### ISSUE THREAD

**Issue by osdiab** [unsplash/intlc#202]
More of an FYI, but I made this [`asdf` plugin](https://github.com/asdf-vm/asdf) to install `intlc`.

https://github.com/osdiab/asdf-intlc

so as an alternative to downloading the binary directly, you can use `asdf` for you/your team to install it locally. Hope this helps someone!

**Comment by samhh** [comment]
Thanks! Hopefully we'll have a Nix derivation at some point as well (related: #99).
